PlasmoHQ/docs

src/pages/index.mdx

This PR updates a link to the customisation of a `/src` directory for a plasmo app. It currently contains outdated/wrong breadcrumbs.

fix: link to `src` directory guide

---

src/pages/framework/storage.mdx

I think it should be mentioned in the documentation that any JSON-ifiable value can be stored without needing to serialize and deserialize it yourself.

Add another example for the storage API

---

src/pages/framework/customization/src.mdx

Fixed a link on the [src page](https://docs.plasmo.com/framework/customization/src) to a non-existent page.

doc: fix link on src page

---

src/pages/framework/content-scripts-ui/life-cycle.mdx

Type definition for `PlasmoCSUIAnchor` returns an object with attributes of `element` and `type`. It does not have an `anchor` attribute.
This PR updates docs to match.

Fix typo for PlasmoGetShadowHostId

---

src/pages/framework/content-scripts-ui/styling.mdx

I've made updates to the docs related to the following issue that I reported.
https://github.com/PlasmoHQ/plasmo/issues/416

Add Edge Case for Overriding Shadow-DOM Styles

---

src/pages/framework/content-scripts-ui/styling.mdx
src/pages/framework/content-scripts.mdx
src/pages/framework/env.mdx
src/pages/framework/messaging.mdx
src/pages/quickstarts/migrate-to-plasmo.mdx

I noticed that `PlasmoContentScript` was deprecated and renamed to `PlasmoCSConfig`. This replaces each instance in the docs to match.

Migrate to PlasmoCSConfig

---

src/pages/framework/customization/internal-path.mdx

The correct flag is `--src-path`. The docs were updated but the example code was not. This simply updates the example code to use `--src-path`.

Fix src path flag name in the example

---

src/pages/framework/messaging.mdx

Adds missing example of getPort usage

messaging: add example using getPort within a Svelte component

---

src/pages/framework/content-scripts-ui/life-cycle.mdx

Fixed a link on the [Life Cycle page's update position example](https://docs.plasmo.com/framework/content-scripts-ui/life-cycle#update-position) to a non-existent page.

doc: fix link for an example

---

src/pages/quickstarts/migrate-to-plasmo.mdx

React component is imported as `Popup` but rendered as `<PopupApp/>`. Made simple fix to align with import name -> `<Popup/>`

fix code typo in Quickstarts > Migrate to Plasmo

---

src/pages/framework/customization/src.mdx

Removes `.plasmo/**/*` from `includes` in `tsconfig.json` as mentioned in the comment:  https://github.com/PlasmoHQ/plasmo/issues/274#issuecomment-1293202261.
Adds `.plasmo/index.d.ts` because it is included in default.
https://github.com/PlasmoHQ/plasmo/blob/44b723f3013d0e5e43619436688a0be4dd747858/packages/init/templates/tsconfig.json#L4
I checked other files and found that the alias page had several `tsconfig.json` but didn't include both `.plasmo/**/*` and `.plasmo/index.d.ts`. I was unsure if it was a problem, so I ignored it.
https://github.com/PlasmoHQ/docs/blob/main/src/pages/framework/customization/alias.mdx

Update `tsconfig.json` in `customization/src.mdx`

---

src/pages/framework/workflows/dev.mdx

Adds a new section to the docs following https://github.com/PlasmoHQ/plasmo/pull/745 that details how to change the hostname and port for the dev server and HMR.

Add new documentation about specifying dev server hostname and port

---

src/pages/framework/storage.mdx

This is a copy+paste from the PlasmoHQ/storage README.md. The development note should be in the main documentation as a user will likely encounter the bug well before they get the addon published or start diving into the individual packages.

doc: add firefox note for storage api

---

src/pages/framework/background-service-worker.mdx

Service worker in `dev` mode will always remain `active`, and when I load the `prod` mode extension in chrome, it quickly becomes `inactive`.
It took me some time to realize that this was not a bug written by me.🤣

doc: Service worker in dev mode will always remain active

---

src/pages/framework/assets.mdx

I ran into this issue and it took quite a while to figure out, hence I added a new section for this use case.

docs: add asset > runtime access setup

---

src/pages/framework/customization/src.mdx

Some users may accidentally move the assets directory to the src directory, which will cause `pnpm run dev` to fail.
https://github.com/PlasmoHQ/plasmo/issues/825

docs: add notification when using the src directory with assets

---

src/pages/framework/ext-pages.mdx

Sidepanel landed in [#651](https://github.com/PlasmoHQ/plasmo/pull/651), but the corresponding docs are missing. This PR adds basic information about Sidepanel in the extension pages docs with a link to the example usage. 
> P.S: I thought of adding an entire page dedicated to Side Panel, but I'm unaware of the structure that needs to be followed. If any contributor can point me to the right direction, I shall update this PR with dedicated Sidepanel docs as well.  
fixes: https://github.com/PlasmoHQ/plasmo/issues/783
- (OPTIONAL) Discord ID:
If your PR is accepted, we will award you with the `Contributor` role on Discord server.
To join the server, visit: https://www.plasmo.com/s/d

docs: add sidepanel to extension pages docs

---

src/pages/framework/storage.mdx

I've spent a significant time trying to find out, why my storage-watcher was not responding to changes made in my Popup. The build folder needs to be be deleted, in order to apply changes made in the PlasmoCSConfig; this made debugging not easier. A note, which states that the Storage API is not available in the main-world, would have saved me a ton of time.
I assume other users have the same point of view, as you can see in the following issues:
- #57 (particulary this one)
- #60
- #48

add note about storage api being used in main world

---

src/pages/quickstarts/with-firebase-authentication.mdx

I made a simple fix to remove one of the duplicated definitions of the logout function.

fix code typo in Quickstarts > Quickstart with Firebase Auth

---

src/pages/quickstarts/with-tailwindcss.mdx

This change aims to help developers avoid potential issues with CSS variables in CSUI with the built-in `Root Container`. It provides additional information on how to handle CSS variables when using Tailwind and its plugins, which often rely on the `:root` selector. 
The update includes a specific example of how to replace the `:root` scope with `:host` before attaching the style to the shadow DOM, especially when using a Tailwind plugin like [DaisyUI](https://daisyui.com/).

Improve Tailwind CSS Usage in Content Scripts UI

---

src/pages/framework/content-scripts-ui/life-cycle.mdx

This documentation update shows how to use dynamically created containers and update the system observer with the new container. 
Without this information, an infinite loop is created resulting in the container being inserted in the page multiple times.
This on discussed on issue PlasmoHQ/Plasmo#1008

Update life-cycle.mdx - Add how to dynamically create rootContainers

---

src/pages/framework/messaging.mdx

In this PR, I fixed an issue where `addListener` and `removeListener` were not using the same reference for the listener function. 
This caused the removal of the listener to fail, as `removeListener` requires the exact function reference that was initially passed to `addListener`. 
To resolve this, I stored the listener function in a variable and reused it for both adding and removing the listener.

fix: listener removal in port docs
